index:
    path: /{_locale}
    controller: App\Controller\TechNews\IndexController::index
    defaults: { _locale: '%locale%' }

home:
    path: /accueil
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: index
        permanent: true

mentions_legales:
    path: /mentions-legales
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: static/mentionslegales.html.twig
